stages:
- dockerize
- build
- deploy

variables:
  PUBLIC_URL: /sia-watermarking-2
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_CACHE_PATH: .cache/docker

cache:
  paths:
  - build

dockerize:
  services:
    - docker:dind
  stage: dockerize
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - CONTAINER_IMAGE=$(echo $CONTAINER_IMAGE | tr '[:upper:]' '[:lower:]')
    - docker build --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest
  when: manual

build:
  image: registry.gitlab.com/zhuvikin/sia-watermarking-2:latest
  stage: build
  script:
  - source $HOME/.bashrc
  - npm install
  - make build-release
  - make test-cli
  artifacts:
    expire_in: 30 mins
    paths:
    - ./build
    - ./out
    - ./target

pages:
  stage: deploy
  before_script:
  - mv public _public
  - mv build public
  - cp public/index.html public/404.html
  script:
  - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
    - public
