[workspace]
members = [
    "lib/sia/rust/cli",
    "lib/sia/rust/watermarking",
    "lib/sia/rust/web",
    "lib/sia/rust/embedding",
    "lib/sia/rust/encoding",
    "lib/sia/rust/feature",
    "lib/sia/rust/three-bit-quantization",
    "lib/sia/rust/signature",
    "lib/sia/rust/utils",
]